# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/fastai-notebooks",
        "doc_host": "https://wouldadam.github.io",
        "git_url": "https://github.com/wouldadam/fastai-notebooks",
        "lib_path": "miniai",
    },
    "syms": {
        "miniai.datasets": {
            "miniai.datasets.get_grid": ("14-huggingface-datasets.html#get_grid", "miniai/datasets.py"),
            "miniai.datasets.show_image": ("14-huggingface-datasets.html#show_image", "miniai/datasets.py"),
            "miniai.datasets.show_images": ("14-huggingface-datasets.html#show_images", "miniai/datasets.py"),
            "miniai.datasets.subplots": ("14-huggingface-datasets.html#subplots", "miniai/datasets.py"),
        },
        "miniai.training": {
            "miniai.training.Dataset": ("14-minibatch-training.html#dataset", "miniai/training.py"),
            "miniai.training.Dataset.__getitem__": (
                "14-minibatch-training.html#dataset.__getitem__",
                "miniai/training.py",
            ),
            "miniai.training.Dataset.__init__": ("14-minibatch-training.html#dataset.__init__", "miniai/training.py"),
            "miniai.training.Dataset.__len__": ("14-minibatch-training.html#dataset.__len__", "miniai/training.py"),
            "miniai.training.accuracy": ("14-minibatch-training.html#accuracy", "miniai/training.py"),
            "miniai.training.fit": ("14-minibatch-training.html#fit", "miniai/training.py"),
            "miniai.training.get_dls": ("14-minibatch-training.html#get_dls", "miniai/training.py"),
        },
    },
}
