# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/fastai-notebooks",
        "doc_host": "https://wouldadam.github.io",
        "git_url": "https://github.com/wouldadam/fastai-notebooks",
        "lib_path": "miniai",
    },
    "syms": {
        "miniai.datasets": {
            "miniai.datasets.get_grid": ("14-huggingface-datasets.html#get_grid", "miniai/datasets.py"),
            "miniai.datasets.show_image": ("14-huggingface-datasets.html#show_image", "miniai/datasets.py"),
            "miniai.datasets.show_images": ("14-huggingface-datasets.html#show_images", "miniai/datasets.py"),
            "miniai.datasets.subplots": ("14-huggingface-datasets.html#subplots", "miniai/datasets.py"),
        }
    },
}
